### ISSUE TITLE
Basic lexer by Alex

### ISSUE THREAD

**Issue by ice1000** [owo-lang/OwO#11]
+ [x] Add `alex` as dependency
+ [x] Layout-based syntax
+ [x] `where`, `postulate`, `instance` that starts new layout
+ [x] Basic tokenize, reserving `[`, `]`, `[|`, `|]`, `{|`, `|}`, `(`, `)`, `=`, `,`, `<-`, `->`, `forall`, `:`
+ [x] Get the `infix` info, but further parsing is left to #12

**Comment by anqurvanillapy** [comment]
I will keep pace with the design by modifying the `misc/Grammar` file in a Backus-Naur-like form.  First off only the declaration of tokens will be considered.

**Comment by ice1000** [comment]
https://github.com/simonmar/alex/blob/master/examples/tiger.x

**Comment by ice1000** [comment]
![utsuho-reiuji-hd-3ed4e0](https://user-images.githubusercontent.com/16398479/48853308-37f07300-ed7d-11e8-89e6-43397ca9a56b.png)
![utsuho-3](https://user-images.githubusercontent.com/16398479/48853316-39ba3680-ed7d-11e8-86d9-02ca89bab1d1.jpg)
![40309438-112b4032-5d3c-11e8-8de8-a7abdffc9a2e](https://user-images.githubusercontent.com/16398479/48853330-40e14480-ed7d-11e8-8e20-46b6a1ab36b5.jpg)
