### ISSUE TITLE
Make EOL opinionated

### ISSUE THREAD

**Issue by anqurvanillapy** [owo-lang/OwO#13]
I remember I forced `stylish-haskell` to format code with LF EOL.  Shall we use a `.gitattributes` with `* text=auto eol=lf` to force it to the whole project?  Or just `newline: auto` in `.stylish-haskell.yaml`?  The warning of unstaged changes due to the EOLs on Windows annoys me a lot.

**Comment by ice1000** [comment]
I think we can.
I'm a windows user and I don't see that issue. Maybe my git config has its own thoughts.
