### ISSUE TITLE
Examples at such an early stage for syntax discussions and parser mock data

### ISSUE THREAD

**Issue by anqurvanillapy** [owo-lang/OwO#16]
Initialize example source files in `examples` directory for discussing everything related to syntax, and it is convenient to test the parser with them as mock data.

**Comment by anqurvanillapy** [comment]
Initialization done at commit https://github.com/owo-lang/OwO/commit/eb709fa9adfbf1380945387ba51ff1b436339c42

**Comment by ice1000** [comment]
Woc

**Comment by ice1000** [comment]
Why

**Comment by ice1000** [comment]
我还在想怎么改intellij-haskell……感觉我把人家图标搞坏了

**Comment by anqurvanillapy** [comment]
> Why

The initialization work of examples is done and symbolic to everybody now (think of #21), so the further work can be gradually completed without this issue hanging up here.

**Comment by ice1000** [comment]
O

**Comment by ice1000** [comment]
Makes a little sense

**Comment by ice1000** [comment]
https://gitter.im/intellij-haskell/Lobby 虎哥化停不下来了
