### ISSUE TITLE
Verbosity of `--dump-tokens`

### ISSUE THREAD

**Issue by anqurvanillapy** [owo-lang/OwO#19]
Phew I'm just a goddamn Haskell newbie, hoowee.  The verbosity of `--dump-tokens` option should be added for more convenient testing, e.g. a *full* verbosity (token type, token value, location) and a *simple* one (only token type and value).

- The interface options are:
    + `--dump-tokens=full` or `--dump-tokens=simple`
    + `-S` for simple, `-SS` for full
    + `--dump-tokens` for full, `--dump-hide-pos` for simple (this is originated from @ice1000, but I thought there could be conflicts here)

The current choice is the **second** one.

**Comment by anqurvanillapy** [comment]
Currently a wrong verbosity level will `ExitFailure` with a `stderr`-based string, which is completely undesirable since showing help text is the best way to elaborate problems.

**Comment by anqurvanillapy** [comment]
Added `--dump-simple` to dump tokens/AST in a concise way (without information like positions), and it can be use to straightly print anything about compiler frontend that eases the mind.

**Comment by ice1000** [comment]
我觉得你理解错我意思了

**Comment by anqurvanillapy** [comment]
Go get 'em bae QAQ
