### ISSUE TITLE
Project-local code-formatting (and possibly custom style)

### ISSUE THREAD

**Issue by anqurvanillapy** [owo-lang/OwO#2]
Candidates:

* stylelish-haskell
* hindent
* ~~brittany~~
* ~~hfmt~~

**Comment by anqurvanillapy** [comment]
Linting might be a go, but now (pre-commit) formatting is fine.

**Comment by ice1000** [comment]
Lihai

**Comment by ice1000** [comment]
Anququ suke

**Comment by OlingCat** [comment]
stylish-haskell?

**Comment by anqurvanillapy** [comment]
> stylish-haskell?

Wow, it looks convenient to configure for a project.  `hindent` is kinda like `autopep8` in Python (which reads stdin and writes to stdout), and if you're familiar with it we need a `black`-like formatter to forget about the pipes.

**Comment by ice1000** [comment]
Sasa's server too slow can't compile

```elisp
(custom-set-variables
 '(haskell-stylish-on-save t))
```

**Comment by anqurvanillapy** [comment]
It’s reading the `stdin` perhaps...  This tool is way too minimal that is able to format a partial file, and I made a temp script to play around at first.  It requires further considerations.  It even delete a whole block of code when I forgot to have CPP included...

**Comment by ice1000** [comment]
The Emacs Lisp code works quite good for me

**Comment by anqurvanillapy** [comment]
In VSCode, there is an extension called "Run On Save" and I left a command to the settings for auto-formatting:

```json
{
  "emeraldwalk.runonsave": {
    "commands": [
        {
            "match": "\\.hs$",
            "cmd": "stylish-haskell -i ${file}"
        }
    ]
  }
}
```
